apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  namespace: icgroup
  labels:
    type: local
    app: odoo
    environment: production
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data-odoo"