apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: icgroup
  labels:
    type: local
    app: postgres
    environment: production
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"