apiVersion: v1
kind: Service
metadata:
  name: icwebappsvc
  labels:
    name: icwebapp
    environment: production
  namespace: icgroup
spec:
  type: LoadBalancer #NodePort
  selector:
    app: icwebapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30080