apiVersion: v1
kind: Service
metadata:
  name: odoosvc
  labels:
    app: odoo
    environment: production
  namespace: icgroup
spec:
  type: NodePort
  selector:
    app: odoo
    tier: frontend
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30069